# Generated by Django 4.2.5 on 2023-10-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='News/image/', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('url', models.URLField(blank=True, verbose_name='Доп. источник')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.category', verbose_name='Категория')),
            ],
        ),
    ]
